Repository dealii/candi, pull requests merged in 2018-10, with the labels that each got.

#95 fix cmake path
  deal.II-toolchain/packages/cmake.package
Labels: bug

#96 add openblas
  candi.cfg
  deal.II-toolchain/packages/openblas.package
  deal.II-toolchain/packages/petsc.package
Labels: enhancement

#101 switch deal.II v9.0.0 -> v9.0.1
  candi.cfg
Labels: version update

#103 opensuse fixes
  deal.II-toolchain/packages/trilinos.package
  deal.II-toolchain/platforms/supported/opensuse15.platform
Labels: bug

#104 update assimp to 4.1.0
  deal.II-toolchain/packages/assimp.package
Labels: bug, version update

#102 git cherry-pick enhancement
  candi.cfg
  candi.sh
  deal.II-toolchain/packages/dealii.package
Labels: enhancement
